---
version: "3.7"
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=$TZ
      - OPENVPN_PROVIDER=$PROVIDER
      - OPENVPN_CONFIG=$CONFIG
      - OPENVPN_USERNAME=$USER
      - OPENVPN_PASSWORD=$PASSWORD
      - LOCAL_NETWORK=$NETWORK
      - TRANSMISSION_SPEED_LIMIT_UP=$SPEED_LIMIT_UP
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - WEBPROXY_ENABLED=false
      - LOG_TO_STDOUT=true
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - PUID=1000
      - PGID=1000
    volumes:
      - $DOWNLOADS:/data
      - /etc/localtime:/etc/localtime:ro

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
    volumes:
      - radarr_config:/config
      - $MOVIES:/movies
      - $DOWNLOADS:/downloads

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
    volumes:
      - sonarr_config:/config
      - $TV:/tv
      - $DOWNLOADS:/downloads

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
    volumes:
      - prowlarr_config:/config
      - $DOWNLOADS/watch:/downloads

volumes:
  radarr_config:
    driver: local
  sonarr_config:
    driver: local
  prowlarr_config:
    driver: local